apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qrcode-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # FastAPI backend (http://<IP>/api/generate-qr/)
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80

          # Next.js frontend (http://<IP>/)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
