name: frontend CI pipeline
on:
  push:
    branches:
      - main           # ✅ Only run on push to main
    paths:
      - 'frontend/**'  # ✅ Only when frontend files change -- both conditions
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  

  code-quality:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: frontend/
          args: >
            -Dsonar.projectKey=gitpranay5_qrcodegenerator
            -Dsonar.organization=gitpranay5
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  docker-build:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set version from run number
        run: echo "VERSION=v${{ github.run_number }}" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/qrcode-frontend:${{ env.VERSION }}

  update-k8s:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set version
        run: echo "VERSION=v${{ github.run_number }}" >> $GITHUB_ENV
      - name: Update tag in kubernetes deployment manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/qrcode-frontend:${{ env.VERSION }}|" k8s/frontend-deployment.yaml
      - name: Commit and push changes
        run: |
          git config --global user.email "pranayjujjuri@gmail.com"
          git config --global user.name "Pranay Jujjuri"
          git add k8s/frontend-deployment.yaml
          git commit -m "Updated deployment image tag to $VERSION" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main